services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php
      MYSQL_USER: user

  # mysql
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql 
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php

  # redis

volumes:
  mysqldata: