name: TranslateThis
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Composer Dependencies
        working-directory: ./app
        run: composer install --prefer-dist
      - name: Run Tests
        working-directory: ./app
        run: composer test
      - run: docker build --target app -t spidermane/php-composer:1.1 -f ./php/Dockerfile .
      - run: docker build -t spidermane/nginx-php:1.0 -f ./nginx/Dockerfile .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -P ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push spidermane/php-composer:1.1
      - run: docker push spidermane/nginx-php:1.0
